### ISSUE TITLE
Gem isn't detected when run from git repo

### ISSUE THREAD

**Issue by edwardsamuel** [poise/poise-ruby-build#2]
I have the following files:

**Gemfile**

```
source 'https://rubygems.org'

gem 'berkshelf'

gem "test-kitchen"
gem "kitchen-vagrant"
gem "poise-ruby-build", github: "poise/poise-ruby-build"
gem "halite"
```

**Berksfile**

```
source "https://supermarket.chef.io"
metadata
extension 'halite'
cookbook 'poise-ruby-build', gem: 'poise-ruby-build'
```

I run `bundle install` and then when I run `vagrant reload --provision`, I got:

```
==> default: Loading Berkshelf datafile...
==> default: Sharing cookbooks with VM
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: Updating Vagrant's Berkshelf...
The following berks command failed to execute:

    /home/edward/.rvm/gems/ruby-2.2.1/bin/berks vendor /home/edward/.berkshelf/vagrant-berkshelf/shelves/berkshelf20160314-3407-oh8ps5-default --berksfile /home/edward/projects/chef-rails-dataplatform/Berksfile

The stdout and stderr are shown below:

    stdout: Resolving cookbook dependencies...
Fetching 'dataplatform' from source at .
Fetching 'poise-ruby-build' from gem from poise-ruby-build

    stderr: /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite/gem.rb:222:in `rescue in dependency_to_spec': Cannot find a gem to satisfy poise-ruby-build (>= 0): Could not find 'poise-ruby-build' (>= 0) among 583 total gem(s) (Halite::Error)
Checked in 'GEM_PATH=/home/edward/.rvm/gems/ruby-2.2.1:/home/edward/.rvm/gems/ruby-2.2.1@global:/home/edward/.vagrant.d/gems/ruby/2.2.0', execute `gem env` for more information
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite/gem.rb:218:in `dependency_to_spec'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite/gem.rb:62:in `spec'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite/gem.rb:57:in `initialize'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite.rb:43:in `new'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/halite.rb:43:in `convert'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/halite-1.2.1/lib/berkshelf/locations/gem.rb:47:in `install'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:184:in `block in download_locations'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:181:in `each'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:181:in `download_locations'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:154:in `install_from_universe'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/installer.rb:39:in `run'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/berksfile.rb:421:in `install'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/berksfile.rb:630:in `block in vendor'
    from /home/edward/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/berksfile.rb:628:in `vendor'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:391:in `vendor'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:52:in `dispatch'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:27:in `execute!'
    from /home/edward/.rvm/gems/ruby-2.2.1/gems/berkshelf-4.3.0/bin/berks:5:in `<top (required)>'
    from /home/edward/.rvm/gems/ruby-2.2.1/bin/berks:23:in `load'
    from /home/edward/.rvm/gems/ruby-2.2.1/bin/berks:23:in `<main>'
    from /home/edward/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/edward/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.

Please download and install the latest version of the ChefDK from:

    https://downloads.chef.io/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

Why I couldn't use this pre-release cookbook? I tried with `poise-application` and it's worked.

**Comment by coderanger** [comment]
When working with Vagrant you are generally using Vagrant's Ruby environment, not your own. So it can't see gems installed to your Ruby. Probably best off cloning the repo, running `bundle install && rake build` and then pointing Berkshelf at the generated cookbook under `pkg/`.
